CREATE DATABASE AGENDA;

GO
USE AGENDA;

CREATE TABLE LEMBRETE
(
    ID INT PRIMARY KEY NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    DATA DATETIME NOT NULL,
    DESCRICAO VARCHAR(250)
);
